# Generated by Django 3.1.3 on 2021-03-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_auto_20210309_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='videostat',
            name='screen_height',
            field=models.CharField(default=1000, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videostat',
            name='screen_width',
            field=models.CharField(default=1000, max_length=200),
            preserve_default=False,
        ),
    ]
