# Generated by Django 3.1.3 on 2021-04-13 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_auto_20210310_1344'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='Stream',
        ),
        migrations.DeleteModel(
            name='VideoStat',
        ),
        migrations.RenameField(
            model_name='stream',
            old_name='video_link',
            new_name='stream_link',
        ),
        migrations.RenameField(
            model_name='stream',
            old_name='video_name',
            new_name='stream_name',
        ),
    ]
