# Generated by Django 3.2 on 2021-04-15 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_streamhighlights'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamhighlights',
            old_name='highlights_urls',
            new_name='clip_link',
        ),
    ]
