# Generated by Django 3.2 on 2021-04-15 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0009_rename_highlights_urls_streamhighlights_clip_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StreamHighlights',
            new_name='StreamHighlight',
        ),
    ]
